In [1]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5]) 
print(arr)

[1 2 3 4 5]


In [2]:

import sys 

S= range(1000) 
print("Size of each element of list in bytes: ", sys.getsizeof(S)) 
print("Size of the whole list in bytes: " , sys.getsizeof(S)*len (S)) 


Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000


In [3]:
arr = np.array(42) 
print(arr) 

42


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr) 


[[1 2 3]
 [4 5 6]]


In [7]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) 
print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
zeros_arr = np.zeros((5,2)) 
eros_arr = np.zeros(5) 
print(zeros_arr) 

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
zeroes=np.zeros((3,3),dtype=np.int64)
print(zeroes)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
empty=np.empty((3,2))
print(empty)
print(empty.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64


In [12]:
empty=np.ones((3,2))
print(empty)
print(empty.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64


In [13]:
empty=np.ones((3,2),dtype=np.int64)
print(empty)
print(empty.dtype)

[[1 1]
 [1 1]
 [1 1]]
int64


In [14]:
identity_matrix=np.eye(4,4)
print("\n",identity_matrix)


 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
identity_matrix=np.eye(4,4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)

[1. 2. 3.] float64
[1 2 3] int32


In [17]:
a=np.array([1,2,3])
print("Before converting:",a,a.dtype)
b=a.astype('f')
print("after converting:",b,b.dtype)

Before converting: [1 2 3] int32
after converting: [1. 2. 3.] float32


In [19]:
arr1=np.arange(10)
arr2=np.random.randn(10)
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)
b=arr1.astype(arr2.dtype)
print(b,b.dtype)
c=b.astype('int')
print(c,c.dtype)

[0 1 2 3 4 5 6 7 8 9] int32
[-1.36710334 -1.04235112 -0.36123023  0.12464679  0.72031845  0.66266921
 -0.36824365  0.62751995 -1.10403    -0.22754526] float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[0 1 2 3 4 5 6 7 8 9] int32


In [20]:
str_arr=np.array(["Hello","world","numpy"])
print(str_arr)

['Hello' 'world' 'numpy']


In [22]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [24]:
import numpy as np 
arr = np.arange(12) 
newarr = arr.reshape(4, 3) 
print(newarr) 
newarr = arr.reshape((4, 3), order='F')
print("\n", newarr) 


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [34]:
original_array = np.array([[10, 20], [30, 40]])
print("Original array:\n", original_array) 
flattened_array = original_array.flatten() 
flattened_array[0] = 999 
print("Flattened array: \n", flattened_array)
print("Original array: \n", original_array) 
raveled_array = original_array.ravel() 
raveled_array [1] = 888 
print("Raveled array: \n", raveled_array)
print("Original array:\n", original_array) 


Original array:
 [[10 20]
 [30 40]]
Flattened array: 
 [999  20  30  40]
Original array: 
 [[10 20]
 [30 40]]
Raveled array: 
 [ 10 888  30  40]
Original array:
 [[ 10 888]
 [ 30  40]]


In [39]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 1], [3, 5]]) 
greater_than = arr1 > arr2 
less_than = arr1 < arr2 
equal_to = arr1 == arr2 
print("Greater than: \n", greater_than)
print("\nLess than: \n", less_than)
print("\nEqual to: \n", equal_to) 
arr3 = np.array([1, 2, 3])
arr4 = np.array([1, 2, 3])
arr5 = np.array([1, 2, 4]) 
result1= np.array_equal(arr3, arr4) 
result2 = np.array_equal(arr3, arr5) # False 
print("\nArray-wise comparison 1:", result1)
print("Array-wise comparison 2:", result2)

Greater than: 
 [[False  True]
 [False False]]

Less than: 
 [[ True False]
 [False  True]]

Equal to: 
 [[False False]
 [ True False]]

Array-wise comparison 1: True
Array-wise comparison 2: False


In [43]:
x = np.arange(10) 
print("x= ",x)
print("\n x[:5]= ",x[:5]) 
print("\n x[5:]= ",x[5:])
print("\n x[::-1]= ",x[::-1])

x=  [0 1 2 3 4 5 6 7 8 9]

 x[:5]=  [0 1 2 3 4]

 x[5:]=  [5 6 7 8 9]

 x[::-1]=  [9 8 7 6 5 4 3 2 1 0]


In [44]:
x2 = np.array([[12, 5, 2, 4], [ 7, 6, 8, 8], [ 1, 6, 7, 7]]) 
print(x2[0])
print(x2[1] [2])
print(x2 [2, -1])
print(x2[0]) 

[12  5  2  4]
8
7
[12  5  2  4]


In [45]:
x2 = np.array([[12, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]]) 
print("x2= ",x2)
print("\n x2[:2, :3] = \n",x2[:2, :3]) 
print("\n x2[:3, ::2]=\n",x2[:3, ::2])  
print("\n x2[::-1,::-1]= \n",x2[::-1, ::-1])

x2=  [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

 x2[:2, :3] = 
 [[12  5  2]
 [ 7  6  8]]

 x2[:3, ::2]=
 [[12  2]
 [ 7  8]
 [ 1  7]]

 x2[::-1,::-1]= 
 [[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


In [46]:
import numpy as np 
a = np.arange(12). reshape (3,4) 
print("a= \n",a) 
b = a > 4 
print("b= \n", b) 
print("a[b]= \n",a[b])
a [b] = 1 
print("a= \n",a)

a= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b= 
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
a[b]= 
 [ 5  6  7  8  9 10 11]
a= 
 [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [48]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.arange(28). reshape(7, 4) 
print(names) 
print("data= \n", data) 
print("names bool= \n", names == 'Bob')
print("names == 'Bob' \n", data [names == 'Bob']) 

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
names bool= 
 [ True False False  True False False False]
names == 'Bob' 
 [[ 0  1  2  3]
 [12 13 14 15]]


In [49]:
import numpy as np

arr = np.arange(32).reshape(8, 4)
print("arr= \n", arr)

print("\narr[[1, 5, 7, 2]]= \n", arr[[1, 5, 7, 2]])

print("\narr[[1, 5, 7, 2], [0, 3, 1, 2]]= \n", arr[[1, 5, 7, 2], [0, 3, 1, 2]])

print("\narr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]= \n", arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

print("\narr[[-3, -5, -7]]\n", arr[[-3, -5, -7]])

arr[[1, 5, 7, 2]] = 1
print("\narr after modification= \n", arr)

arr= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

arr[[1, 5, 7, 2]]= 
 [[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

arr[[1, 5, 7, 2], [0, 3, 1, 2]]= 
 [ 4 23 29 10]

arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]= 
 [[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]

arr[[-3, -5, -7]]
 [[20 21 22 23]
 [12 13 14 15]
 [ 4  5  6  7]]

arr after modification= 
 [[ 0  1  2  3]
 [ 1  1  1  1]
 [ 1  1  1  1]
 [12 13 14 15]
 [16 17 18 19]
 [ 1  1  1  1]
 [24 25 26 27]
 [ 1  1  1  1]]


In [50]:
import numpy as np 
arr = np.arange(12).reshape((3, 4)) 
print(arr) 
print("Transpose using .T") 
print(arr.T) 
print("Transpose using the transpose() function") 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose using .T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Transpose using the transpose() function


In [51]:
import numpy as np 
arr = np.arange(12).reshape((3, 4))
print("Dot product of arr and arr2:")
print(np.dot(arr, arr.T)) 


Dot product of arr and arr2:
[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [52]:
arr = np.arange(12).reshape((3, 4)) 
print(arr) 
print("Swap axes 0 and 1:") 
print(np.swapaxes (arr, 0, 1)) 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swap axes 0 and 1:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [55]:
import numpy as np 
arr1 = np.array([[1, 2], 
[3, 4]]) 
arr2 = np.array([[5, 6], 
[7, 8]]) 
result = np.multiply(arr1, arr2) 

print("Result of element-wise multiplication:")
print(result) 
result = np.matmul (arr1, arr2) 
print("Result of matrix multiplication:")
print(result) 


Result of element-wise multiplication:
[[ 5 12]
 [21 32]]
Result of matrix multiplication:
[[19 22]
 [43 50]]
